import './globals.css';
import localFont from 'next/font/local';

const Madimi = localFont({
  src: '../public/fonts/MadimiOne-Regular.ttf',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={Madimi.className}>{children}</body>
    </html>
  );
}
